// frontend/vite/src/tsx/App.tsx
import React, { createContext, useState, useContext, useEffect } from 'react';
import ExampleComponent from './components/ExampleComponent';
import { createBrowserRouter, RouterProvider } from 'react-router-dom';
import Home from './pages/Home';

// store
const storeData = {
  message: 'Hello World'
};
const Context = createContext<{ message: string } | null>(null);

// route
const routes = createBrowserRouter([
  {
    path: '/',
    element: <Home />
  }
]);

const App = (): React.JSX.Element => {
  const [text, setText] = useState('ExampleComponent');
  const [context, setContext] = useState(storeData);
  console.log(`React is ready. ${context.message}`);
  useEffect(() => {
    setContext({ message: 'state updated' });
  }, []);
  return (
    <>
      <Context.Provider value={context}>
        <RouterProvider router={routes} />
        <ExampleComponent message={text} />
      </Context.Provider>
    </>
  );
};

// eslint-disable-next-line react-refresh/only-export-components
export function useSampleContext() {
  return useContext(Context);
}

export default App;

// frontend/astro/src/vue/App.vue
<script lang="ts" setup>
import { reactive } from 'vue';
import { useStore } from '@/scripts/store';
import ExampleComponent from '@/vue/components/ExampleComponent.vue';
const store = useStore();
const data = reactive({
  text: 'This is ExampleComponent (Vue.js)'
});
store.updateMessage('state updated.');
// eslint-disable-next-line no-console
console.log(`Vue.js is ready. ${store.message}`);
</script>

<template>
  <router-view />
  <example-component :message="data.text" />
</template>
